name: WBPlugin
main: dev.WBPlugin
version: 1.0
api-version: 1.14
commands:
  bomb:
    description: enable / disable snow-bombs
    usage: /bomb <on | off | radius | power> [radius | power]
  prgn:
    description: create, modify, and delete protected regions
    usage: /prgn <create | delete | list | test>